name: coverage
on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master 
permissions: write-all
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3

      - name: generate test coverage
        run: go test ./... -coverprofile=./cover.out -covermode=atomic -coverpkg=./...

      - name: check test coverage
        uses: vladopajic/go-test-coverage@v2
        with:
          profile: cover.out
          local-prefix: github.com/m0t9/meanind
          threshold-total: 80

          git-token: ${{ github.ref_name == 'master' && secrets.GITHUB_TOKEN || '' }}
          git-branch: badges
